# Generated by Django 3.2.7 on 2021-10-22 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller_products', '0007_auto_20211015_2104'),
        ('sales', '0005_auto_20211022_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_product', to='sales.sale')),
                ('seller_product_archive_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_product', to='seller_products.sellerproductarchive')),
            ],
            options={
                'verbose_name': 'SaleProduct',
                'verbose_name_plural': 'SaleProducts',
                'db_table': 'sale_products',
                'ordering': ('sale_id',),
            },
        ),
    ]
