# Generated by Django 3.2.7 on 2021-10-22 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_saleproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleproduct',
            old_name='seller_product_archive_id',
            new_name='seller_product_archive',
        ),
    ]
