# Generated by Django 3.2.7 on 2021-09-05 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0004_auto_20210905_1349'),
        ('geo_regions', '0001_initial'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Data Sample')),
                ('descr', models.TextField(blank=True, default='', verbose_name='Description')),
                ('path', models.FilePathField(max_length=255, verbose_name='Path to data sample')),
            ],
            options={
                'verbose_name': 'Data sample',
                'verbose_name_plural': 'Data samples',
                'db_table': 'data_samples',
            },
        ),
        migrations.CreateModel(
            name='DataUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Data url')),
                ('descr', models.TextField(blank=True, default='', verbose_name='Description')),
                ('url', models.URLField(verbose_name='Path to data sample')),
            ],
            options={
                'verbose_name': 'Data url',
                'verbose_name_plural': 'Data urls',
                'db_table': 'data_urls',
            },
        ),
        migrations.CreateModel(
            name='SellerProductArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Product for sale')),
                ('descr', models.TextField(blank=True, default='', verbose_name='Description')),
                ('price_per_one_time', models.FloatField(blank=True, default=None, verbose_name='Price per one time usage')),
                ('price_per_month', models.FloatField(blank=True, default=None, verbose_name='Price per month')),
                ('price_per_year', models.FloatField(blank=True, default=None, verbose_name='Price per year')),
                ('price_by_request', models.FloatField(blank=True, default=None, verbose_name='Price by request')),
                ('price_per_usage', models.BooleanField(blank=True, default=None, verbose_name='Price per usage True/False')),
                ('price_per_usage_descr', models.TextField(blank=True, default=None, verbose_name='Purhcase method description')),
                ('rating', models.FloatField(blank=True, default=None, null=True, verbose_name='Rating')),
                ('total_reviews_cnt', models.IntegerField(verbose_name='Total count of reviews')),
                ('version', models.IntegerField(default=1, verbose_name='Version')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('categories', models.ManyToManyField(blank=True, related_name='seller_products_archive', to='categories.Category', verbose_name='Content categories')),
                ('data_samples', models.ManyToManyField(blank=True, related_name='seller_products_archive', to='seller_products.DataSample', verbose_name='Content data samples')),
                ('data_urls', models.ManyToManyField(blank=True, related_name='seller_products_archive', to='seller_products.DataUrl', verbose_name='Content data urls')),
                ('geo_regions', models.ManyToManyField(blank=True, related_name='seller_products_archive', to='geo_regions.GeoRegion', verbose_name='Content geo-regions')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_archive', to='sellers.seller')),
            ],
            options={
                'db_table': 'seller_products_archive',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Product for sale')),
                ('descr', models.TextField(blank=True, default='', verbose_name='Description')),
                ('price_per_one_time', models.FloatField(blank=True, default=None, verbose_name='Price per one time usage')),
                ('price_per_month', models.FloatField(blank=True, default=None, verbose_name='Price per month')),
                ('price_per_year', models.FloatField(blank=True, default=None, verbose_name='Price per year')),
                ('price_by_request', models.FloatField(blank=True, default=None, verbose_name='Price by request')),
                ('price_per_usage', models.BooleanField(blank=True, default=None, verbose_name='Price per usage True/False')),
                ('price_per_usage_descr', models.TextField(blank=True, default=None, verbose_name='Purhcase method description')),
                ('rating', models.FloatField(blank=True, default=None, null=True, verbose_name='Rating')),
                ('total_reviews_cnt', models.IntegerField(verbose_name='Total count of reviews')),
                ('version', models.IntegerField(default=1, verbose_name='Version')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('categories', models.ManyToManyField(blank=True, related_name='seller_products', to='categories.Category', verbose_name='Content categories')),
                ('data_samples', models.ManyToManyField(blank=True, related_name='seller_products', to='seller_products.DataSample', verbose_name='Content data samples')),
                ('data_urls', models.ManyToManyField(blank=True, related_name='seller_products', to='seller_products.DataUrl', verbose_name='Content data urls')),
                ('geo_regions', models.ManyToManyField(blank=True, related_name='seller_products', to='geo_regions.GeoRegion', verbose_name='Content geo-regions')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sellers.seller')),
            ],
            options={
                'db_table': 'seller_products',
                'abstract': False,
            },
        ),
    ]
