# Generated by Django 3.2.7 on 2021-09-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('seller_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerproduct',
            name='languages',
            field=models.ManyToManyField(blank=True, db_table='seller_product_languages', to='languages.Language', verbose_name='Content languages'),
        ),
        migrations.AddField(
            model_name='sellerproductarchive',
            name='languages',
            field=models.ManyToManyField(blank=True, db_table='seller_product_languages_archive', to='languages.Language', verbose_name='Content languages'),
        ),
    ]
