# Generated by Django 3.2.7 on 2021-10-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_products', '0003_auto_20210920_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerproductdatasample',
            name='url',
        ),
        migrations.AddField(
            model_name='sellerproductdatasample',
            name='file',
            field=models.FileField(default='', upload_to='seller_product_data_samples/'),
            preserve_default=False,
        ),
    ]
