# Generated by Django 3.2.7 on 2021-10-06 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_delivery_types', '0001_initial'),
        ('seller_products', '0003_auto_20210920_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerproductdatasample',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='sellerproductdatasamplearchive',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='sellerproductdataurl',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='sellerproductdataurlarchive',
            name='data_type',
        ),
        migrations.AddField(
            model_name='sellerproductdatasample',
            name='data_delivery_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='data_delivery_types.datadeliverytype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerproductdatasamplearchive',
            name='data_delivery_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='data_delivery_types.datadeliverytype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerproductdataurl',
            name='data_delivery_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='data_delivery_types.datadeliverytype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerproductdataurlarchive',
            name='data_delivery_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data_delivery_types.datadeliverytype'),
            preserve_default=False,
        ),
    ]
