# Generated by Django 3.2.7 on 2021-10-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_products', '0004_auto_20211006_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerproductdatasamplearchive',
            name='url',
        ),
        migrations.AddField(
            model_name='sellerproductdatasamplearchive',
            name='file',
            field=models.FileField(default='', upload_to='seller_product_data_samples_archive/'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='sellerproductdatasample',
            name='url',
        ),
        migrations.AddField(
            model_name='sellerproductdatasample',
            name='file',
            field=models.FileField(default='', upload_to='seller_product_data_samples/'),
            preserve_default=False,
        ),
    ]
