# Generated by Django 3.2.7 on 2021-10-07 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_data_types', '0001_initial'),
        ('data_delivery_types', '0001_initial'),
        ('seller_products', '0005_auto_20211004_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproductdatasample',
            name='data_delivery_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_delivery_types.datadeliverytype'),
        ),
        migrations.AlterField(
            model_name='sellerproductdatasample',
            name='data_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_data_types.dataformat'),
        ),
        migrations.AlterField(
            model_name='sellerproductdatasamplearchive',
            name='data_delivery_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_delivery_types.datadeliverytype'),
        ),
        migrations.AlterField(
            model_name='sellerproductdatasamplearchive',
            name='data_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_data_types.dataformat'),
        ),
        migrations.AlterField(
            model_name='sellerproductdataurl',
            name='data_delivery_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_delivery_types.datadeliverytype'),
        ),
        migrations.AlterField(
            model_name='sellerproductdataurl',
            name='data_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_data_types.dataformat'),
        ),
        migrations.AlterField(
            model_name='sellerproductdataurlarchive',
            name='data_delivery_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_delivery_types.datadeliverytype'),
        ),
        migrations.AlterField(
            model_name='sellerproductdataurlarchive',
            name='data_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_data_types.dataformat'),
        ),
    ]
