# Generated by Django 3.2.7 on 2021-11-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_products', '0008_auto_20211022_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproduct',
            name='price_per_usage_descr',
            field=models.TextField(blank=True, default='', verbose_name='Purchase method description'),
        ),
        migrations.AlterField(
            model_name='sellerproductarchive',
            name='price_per_usage_descr',
            field=models.TextField(blank=True, default='', verbose_name='Purchase method description'),
        ),
    ]
