# Generated by Django 3.2.6 on 2021-08-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20210830_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True, verbose_name='For whom is recommended')),
            ],
            options={
                'db_table': 'recommended_for',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='recommended_for',
            field=models.ManyToManyField(blank=True, related_name='categories', to='categories.RecommendedFor', verbose_name='For whom category is recommended'),
        ),
    ]
