# Generated by Django 3.2.7 on 2021-09-05 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20210830_2256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('sort_id', 'name'), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='recommendedfor',
            options={'verbose_name': 'Recommended for', 'verbose_name_plural': 'Recommended for'},
        ),
    ]
