# Generated by Django 3.2.7 on 2021-10-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20210905_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='short_descr',
            field=models.TextField(blank=True, default='', verbose_name='Short description'),
        ),
    ]
