# Generated by Django 3.2.7 on 2021-10-01 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import upload.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_data_types', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.FileField(upload_to=upload.models.PathAndRename('uploaded_tmp/'))),
                ('file_name_original', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_by', to=settings.AUTH_USER_MODEL)),
                ('data_format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_data_types.dataformat')),
                ('data_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_data_types.datatype')),
            ],
            options={
                'verbose_name': 'Uploaded File',
                'verbose_name_plural': 'Uploaded Files',
                'db_table': 'uploaded_files',
            },
        ),
    ]
