# Generated by Django 3.2.7 on 2021-10-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='description',
            new_name='descr',
        ),
    ]
