# Generated by Django 3.2.7 on 2021-09-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('type',), 'verbose_name_plural': 'Seller contacts'},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='seller_id',
            new_name='seller',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='type_id',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='seller_id',
            new_name='seller',
        ),
    ]
