# Generated by Django 3.2.7 on 2021-10-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_rename_description_seller_descr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='descr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL link to logo', max_length=1000, null=True, verbose_name='Logo URL'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='wallet_for_payments_erc20',
            field=models.CharField(blank=True, max_length=42, null=True, verbose_name='ERC-20 wallet'),
        ),
    ]
