# Generated by Django 3.2.7 on 2021-10-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_alter_seller_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='logo_url',
            field=models.FileField(blank=True, help_text='Logo', null=True, upload_to='seller_logo/', verbose_name='Logo'),
        ),
    ]
