# Generated by Django 3.2.7 on 2021-11-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_rename_logo_url_seller_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('type_id',), 'verbose_name_plural': 'Seller contacts'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='type',
        ),
        migrations.AddField(
            model_name='contact',
            name='type_id',
            field=models.IntegerField(choices=[(1, 'URL'), (2, 'Phone'), (3, 'Email')], default=1, verbose_name='Contact type'),
            preserve_default=False,
        ),
    ]
