# Generated by Django 3.2.7 on 2021-09-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataDeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=190, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Data Delivery Type',
                'verbose_name_plural': 'Data Delivery Types',
                'db_table': 'data_delivery_types',
                'ordering': ('name',),
            },
        ),
    ]
