# Generated by Django 3.2.6 on 2021-08-31 22:47

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=190, verbose_name='Name')),
                ('iso_code', models.CharField(max_length=3, unique=True, verbose_name='ISO Code')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='reference.georegion')),
            ],
            options={
                'verbose_name': 'GeoRegion',
                'verbose_name_plural': 'GeoRegions',
                'db_table': 'geo_regions',
            },
        ),
    ]
